interface OutboxOperation{id:string;path:string;method:string;body:string|null;createdAt:string;attempts:number}
const DB='turtle-outbox',STORE='operations';
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE,{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function transaction<T>(mode:IDBTransactionMode,action:(store:IDBObjectStore,done:(value:T)=>void,fail:(error:unknown)=>void)=>void):Promise<T>{const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,mode);action(tx.objectStore(STORE),resolve,reject);tx.oncomplete=()=>db.close();tx.onerror=()=>reject(tx.error);});}
function changed():void{if(typeof window!=='undefined')window.dispatchEvent(new Event('turtle-outbox-change'));}
export async function enqueue(operation:OutboxOperation):Promise<void>{await transaction<void>('readwrite',(store,done,fail)=>{const request=store.put(operation);request.onsuccess=()=>done();request.onerror=()=>fail(request.error);});changed();}
async function all():Promise<OutboxOperation[]>{return transaction<OutboxOperation[]>('readonly',(store,done,fail)=>{const request=store.getAll();request.onsuccess=()=>done(request.result as OutboxOperation[]);request.onerror=()=>fail(request.error);});}
async function remove(id:string):Promise<void>{await transaction<void>('readwrite',(store,done,fail)=>{const request=store.delete(id);request.onsuccess=()=>done();request.onerror=()=>fail(request.error);});changed();}
export async function pendingOutboxCount():Promise<number>{return (await all()).length;}
export async function flushOutbox():Promise<number>{let completed=0;for(const operation of (await all()).sort((a,b)=>a.createdAt.localeCompare(b.createdAt))){try{const response=await fetch(operation.path,{method:operation.method,headers:{'Content-Type':'application/json','Idempotency-Key':operation.id},body:operation.body});if(!response.ok&&response.status<500)throw new Error(`持久化请求失败：${response.status}`);if(!response.ok)break;await remove(operation.id);completed++;}catch{break;}}return completed;}
export async function durableJson<T>(path:string,options:RequestInit,optimistic:T):Promise<{value:T;queued:boolean}>{const id=crypto.randomUUID(),headers=new Headers(options.headers);headers.set('Content-Type','application/json');headers.set('Idempotency-Key',id);try{const response=await fetch(path,{...options,headers});if(!response.ok){const body=await response.json().catch(()=>({error:{message:'请求失败'}})) as any;throw new Error(body.error?.message??`请求失败（${response.status}）`);}return{value:await response.json() as T,queued:false};}catch(error){if(error instanceof TypeError){await enqueue({id,path,method:options.method??'POST',body:typeof options.body==='string'?options.body:null,createdAt:new Date().toISOString(),attempts:0});return{value:optimistic,queued:true};}throw error;}}
if(typeof window!=='undefined')window.addEventListener('online',()=>{void flushOutbox();});
