import { BrowserTranscriptionProvider, createBrowserRecognition, type DiagnosticEvent, type SpeechCallbacks, type SpeechStatus } from './speech';
type Listener=(state:TranscriptionState)=>void;
export interface TranscriptionState{status:SpeechStatus;detail:string;interim:string;events:DiagnosticEvent[]}
class TranscriptionController {
  private state:TranscriptionState={status:'idle',detail:'',interim:'',events:[]};private listeners=new Set<Listener>();private finalHandler:(text:string)=>void=()=>{};private sessionId:string|null=null;private wakeLock:any=null;private provider=new BrowserTranscriptionProvider(createBrowserRecognition(),this.callbacks());
  constructor(){if(typeof window!=='undefined'){document.addEventListener('visibilitychange',()=>{this.record('visibilitychange',document.visibilityState);if(document.visibilityState==='visible'){this.provider.checkHealth();void this.requestWakeLock();}});window.addEventListener('focus',()=>{this.record('focus');this.provider.checkHealth();});window.addEventListener('blur',()=>this.record('blur'));}}
  private callbacks():SpeechCallbacks{return{onInterim:(interim)=>this.update({interim}),onFinal:(text)=>this.finalHandler(text),onStatus:(status,detail='')=>this.update({status,detail}),onEvent:(event)=>{this.state={...this.state,events:[event,...this.state.events].slice(0,100)};this.emit();void this.persist(event);}};}
  subscribe(listener:Listener):()=>void{this.listeners.add(listener);listener(this.state);return()=>this.listeners.delete(listener);}setSession(sessionId:string|null,onFinal:(text:string)=>void):void{this.sessionId=sessionId;this.finalHandler=onFinal;}start():void{this.provider.start();void this.requestWakeLock();}pause():void{this.provider.pause();void this.releaseWakeLock();}stop():void{this.provider.stop();void this.releaseWakeLock();}check():void{this.provider.checkHealth();}
  private update(patch:Partial<TranscriptionState>):void{this.state={...this.state,...patch};this.emit();}private emit():void{for(const listener of this.listeners)listener(this.state);}private record(type:DiagnosticEvent['type'],detail=''):void{const event={type,detail,occurredAt:new Date().toISOString()};this.state={...this.state,events:[event,...this.state.events].slice(0,100)};this.emit();void this.persist(event);}
  private async persist(event:DiagnosticEvent):Promise<void>{try{await fetch('/api/transcription/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:this.sessionId,eventType:event.type,detail:event.detail,occurredAt:event.occurredAt})});}catch{/* Diagnostics never interrupt transcription. */}}
  private async requestWakeLock():Promise<void>{if(!this.provider.wantsListening()||document.visibilityState!=='visible'||!(navigator as any).wakeLock||this.wakeLock)return;try{this.wakeLock=await (navigator as any).wakeLock.request('screen');this.wakeLock.addEventListener('release',()=>{this.wakeLock=null;});}catch{/* Unsupported or denied wake lock degrades normally. */}}
  private async releaseWakeLock():Promise<void>{try{await this.wakeLock?.release();}finally{this.wakeLock=null;}}
}
export const transcriptionController=new TranscriptionController();
